include:
  - board: seeeduino_xiao_ble
    shield: totem_left
    shield: hummingbird rgbled_adapter
    snippet: zmk-usb-logging
  - board: seeeduino_xiao_ble
    shield: totem_right
    shield: hummingbird rgbled_adapter
    snippet: zmk-usb-logging
# there is no settingsreset (needed) for the XIAO
